In [ ]:
!pip install transformers datasets evaluate accelerate scikit-learn pandas

Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (5.0.0)
Requirement already satisfied: datasets in /usr/local/lib/python3.12/dist-packages (4.0.0)
Collecting evaluate
  Downloading evaluate-0.4.6-py3-none-any.whl.metadata (9.5 kB)
Requirement already satisfied: accelerate in /usr/local/lib/python3.12/dist-packages (1.13.0)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (1.6.1)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from transformers) (3.29.0)
Requirement already satisfied: huggingface-hub<2.0,>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (1.11.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (26.1)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.22.2)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from transformers) (0.24.0)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers) (4.67.3)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (18.1.0)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.3.8)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.12/dist-packages (from datasets) (2.32.4)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets) (3.6.0)
Requirement already satisfied: multiprocess<0.70.17 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.70.16)
Requirement already satisfied: fsspec<=2025.3.0,>=2023.1.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (2025.3.0)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from accelerate) (5.9.5)
Requirement already satisfied: torch>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from accelerate) (2.10.0+cu128)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.1)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (3.13.5)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (1.4.3)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (0.28.1)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (0.24.2)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (4.15.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (3.13)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (2026.4.22)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (3.1.6)
Requirement already satisfied: cuda-bindings==12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.9.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (3.4.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (1.13.1.3)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (3.6.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings==12.9.4->torch>=2.0.0->accelerate) (1.5.3)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.23.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (4.13.0)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (0.16.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=2.0.0->accelerate) (1.3.0)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers) (8.3.3)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers) (0.0.4)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=2.0.0->accelerate) (3.0.3)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub<2.0,>=1.3.0->transformers) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub<2.0,>=1.3.0->transformers) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface-hub<2.0,>=1.3.0->transformers) (0.1.2)
Downloading evaluate-0.4.6-py3-none-any.whl (84 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.1/84.1 kB 3.4 MB/s eta 0:00:00
Installing collected packages: evaluate
Successfully installed evaluate-0.4.6

In [ ]:
import pandas as pd
import numpy as np
import requests

from datasets import Dataset
from transformers import AutoTokenizer
from transformers import AutoModelForSequenceClassification
from transformers import TrainingArguments, Trainer

from sklearn.metrics import accuracy_score, classification_report
from sklearn.model_selection import train_test_split

In [ ]:
BASE_URL = "https://rest.uniprot.org/uniprotkb/search"

def download_uniprot_class(query, label_name, label_id, size=100):
    params = {
        "query": query,
        "format": "tsv",
        "fields": "accession,protein_name,gene_names,organism_name,length,sequence",
        "size": size
    }

    response = requests.get(BASE_URL, params=params)

    if response.status_code != 200:
        print("Error:", response.status_code)
        print(response.text)
        return None

    df = pd.read_csv(pd.io.common.StringIO(response.text), sep="\t")
    df["label_name"] = label_name
    df["label"] = label_id

    return df

In [ ]:
kinase_df = download_uniprot_class(
    query='reviewed:true AND protein kinase',
    label_name='kinase',
    label_id=0,
    size=100
)

kinase_df.head()

,Entry,Protein names,Gene Names,Organism,Length,Sequence,label_name,label
0,P19525,"Interferon-induced, double-stranded RNA-activa...",EIF2AK2 PKR PRKR,Homo sapiens (Human),551,MAGDLSAGFFMEELNTYRQKQGVVLKYQELPNSGPPHDRRFTFQVI...,kinase,0
1,Q16539,Mitogen-activated protein kinase 14 (MAP kinas...,MAPK14 CSBP CSBP1 CSBP2 CSPB1 MXI2 SAPK2A,Homo sapiens (Human),360,MSQERPTFYRQELNKTIWEVPERYQNLSPVGSGAYGSVCAAFDTKT...,kinase,0
2,P17948,Vascular endothelial growth factor receptor 1 ...,FLT1 FLT FRT VEGFR1,Homo sapiens (Human),1338,MVSYWDTGVLLCALLSCLLLTGSSSGSKLKDPELSLKGTQHIMQAG...,kinase,0
3,P07948,Tyrosine-protein kinase Lyn (EC 2.7.10.2) (Lck...,LYN JTK8,Homo sapiens (Human),512,MGCIKSKGKDSLSDDGVDLKTQPVRNTERTIYVRDPTSNKQQRPVP...,kinase,0
4,O43318,Mitogen-activated protein kinase kinase kinase...,MAP3K7 TAK1,Homo sapiens (Human),606,MSTASAASSSSSSSAGEMIEAPSQVLNFEEIDYKEIEVEEVVGRGA...,kinase,0

In [ ]:
len(kinase_df)

100

In [ ]:
gpcr_df = download_uniprot_class(
    query='reviewed:true AND G-protein coupled receptor',
    label_name='GPCR',
    label_id=1,
    size=100
)

len(gpcr_df)

100

In [ ]:
gpcr_df.head()

,Entry,Protein names,Gene Names,Organism,Length,Sequence,label_name,label
0,Q8IZF2,Adhesion G protein-coupled receptor F5 (G-prot...,ADGRF5 GPR116 KIAA0758,Homo sapiens (Human),1346,MKSPRRTTLCLMFIVIYSSKAALNWNYESTIHPLSLHEHEPAGEEA...,GPCR,1
1,P47775,G-protein coupled receptor 12,GPR12,Homo sapiens (Human),334,MNEDLKVNLSGLPRDYLDAAAAENISAAVSSRVPAVEPEPELVVNP...,GPCR,1
2,Q9BZJ7,G-protein coupled receptor 62 (G-protein coupl...,GPR62,Homo sapiens (Human),368,MANSTGLNASEVAGSLGLILAAVVEVGALLGNGALLVVVLRTPGLR...,GPCR,1
3,P46089,G-protein coupled receptor 3 (ACCA orphan rece...,GPR3 ACCA,Homo sapiens (Human),330,MMWGAGSPLAWLSAGSGNVNVSSVGPAEGPTGPAAPLPSPKAWDVV...,GPCR,1
4,Q8IZF7,Putative adhesion G protein-coupled receptor F...,ADGRF2P ADGRF2 GPR111 PGR20,Homo sapiens (Human),708,MGLTAYGNRRVQPGELPFGANLTLIHTRAQPVICSKLLLTKRVSPI...,GPCR,1

In [ ]:
ion_df = download_uniprot_class(
    query='reviewed:true AND ion channel',
    label_name='ion_channel',
    label_id=2,
    size=100
)

len(ion_df)

ion_df.head()

,Entry,Protein names,Gene Names,Organism,Length,Sequence,label_name,label
0,Q7NDN8,Proton-gated ion channel (GLIC) (Ligand-gated ...,glvI glr4197,Gloeobacter violaceus (strain ATCC 29082 / PCC...,359,MFPTGWRPKLSESIAASRMLWQPMAAVAVVQIGLLWFSPPVWGQDM...,ion_channel,2
1,Q401N2,Ligand-gated cation channel ZACN (Ligand-gated...,ZACN L2 LGICZ LGICZ1 ZAC,Homo sapiens (Human),412,MMALWSLLHLTFLGFSITLLLVHGQGFQGTAAIWPSLFNVNLSKKV...,ion_channel,2
2,Q5H8A5,Ion channel POLLUX,POLLUX,Lotus japonicus (Lotus corniculatus var. japon...,917,MIPLPVAAANSNSNSNSNSNDEESPNLSTVIKPPLKKTKTLLPPPS...,ion_channel,2
3,Q5H8A6,Ion channel CASTOR,CASTOR,Lotus japonicus (Lotus corniculatus var. japon...,853,MSLDSEVSVSSSSGRDWFFPSPSFFRSSPSQYGRRFHTNSNTHSAP...,ion_channel,2
4,Q9NY37,Bile acid-sensitive ion channel (BASIC) (Acid-...,ASIC5 ACCN5,Homo sapiens (Human),505,MEQTEKSKVYAENGLLEKIKLCLSKKPLPSPTERKKFDHDFAISTS...,ion_channel,2

In [ ]:
combined_df = pd.concat(
    [kinase_df, gpcr_df, ion_df],
    ignore_index=True
)

combined_df = combined_df[["Sequence", "label", "label_name"]]

combined_df.head()

                                            Sequence  label label_name
0  MAGDLSAGFFMEELNTYRQKQGVVLKYQELPNSGPPHDRRFTFQVI...      0     kinase
1  MSQERPTFYRQELNKTIWEVPERYQNLSPVGSGAYGSVCAAFDTKT...      0     kinase
2  MVSYWDTGVLLCALLSCLLLTGSSSGSKLKDPELSLKGTQHIMQAG...      0     kinase
3  MGCIKSKGKDSLSDDGVDLKTQPVRNTERTIYVRDPTSNKQQRPVP...      0     kinase
4  MSTASAASSSSSSSAGEMIEAPSQVLNFEEIDYKEIEVEEVVGRGA...      0     kinase

In [ ]:
print(combined_df.shape)

combined_df["label_name"].value_counts()

(300, 3)

label_name
kinase         100
GPCR           100
ion_channel    100
Name: count, dtype: int64

In [ ]:
combined_df = combined_df.rename(
    columns={"Sequence": "sequence"}
)

train_df, test_df = train_test_split(
    combined_df,
    test_size=0.2,
    stratify=combined_df["label"],
    random_state=42
)

print("Train size:", len(train_df))
print("Test size:", len(test_df))

Train size: 240
Test size: 60

In [ ]:
train_dataset = Dataset.from_pandas(train_df)
test_dataset = Dataset.from_pandas(test_df)

dataset = {
    "train": train_dataset,
    "test": test_dataset
}

dataset

{'train': Dataset({
     features: ['sequence', 'label', 'label_name', '__index_level_0__'],
     num_rows: 240
 }),
 'test': Dataset({
     features: ['sequence', 'label', 'label_name', '__index_level_0__'],
     num_rows: 60
 })}

In [ ]:
model_name = "facebook/esm2_t6_8M_UR50D"

tokenizer = AutoTokenizer.from_pretrained(model_name)

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:93: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

In [ ]:
def tokenize_function(example):
    return tokenizer(
        example["sequence"],
        truncation=True,
        padding="max_length",
        max_length=512
    )

tokenized_train = train_dataset.map(tokenize_function, batched=True)
tokenized_test = test_dataset.map(tokenize_function, batched=True)

In [ ]:
model = AutoModelForSequenceClassification.from_pretrained(
    model_name,
    num_labels=3
)

EsmForSequenceClassification LOAD REPORT from: facebook/esm2_t6_8M_UR50D
Key                         | Status     |
----------------------------+------------+-
lm_head.layer_norm.weight   | UNEXPECTED |
esm.embeddings.position_ids | UNEXPECTED |
lm_head.bias                | UNEXPECTED |
lm_head.layer_norm.bias     | UNEXPECTED |
lm_head.dense.bias          | UNEXPECTED |
lm_head.dense.weight        | UNEXPECTED |
classifier.dense.bias       | MISSING    |
classifier.out_proj.bias    | MISSING    |
classifier.out_proj.weight  | MISSING    |
classifier.dense.weight     | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

In [ ]:
def compute_metrics(eval_pred):
    logits, labels = eval_pred

    predictions = np.argmax(logits, axis=-1)

    accuracy = accuracy_score(labels, predictions)

    return {
        "accuracy": accuracy
    }

In [ ]:
training_args = TrainingArguments(
    output_dir="./drug_target_model",
    eval_strategy="epoch",
    save_strategy="epoch",
    learning_rate=2e-5,
    per_device_train_batch_size=4,
    per_device_eval_batch_size=4,
    num_train_epochs=3,
    weight_decay=0.01,
    logging_dir="./logs",
    report_to="none"
)

`logging_dir` is deprecated and will be removed in v5.2. Please set `TENSORBOARD_LOGGING_DIR` instead.

In [ ]:
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_train,
    eval_dataset=tokenized_test,
    processing_class=tokenizer,
    compute_metrics=compute_metrics
)

In [ ]:
trainer.train()

The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'eos_token_id': 2}.

TrainOutput(global_step=180, training_loss=0.808944108751085, metrics={'train_runtime': 21.9987, 'train_samples_per_second': 32.729, 'train_steps_per_second': 8.182, 'total_flos': 16593674895360.0, 'train_loss': 0.808944108751085, 'epoch': 3.0})

In [ ]:
eval_results = trainer.evaluate()

eval_results

{'eval_loss': 0.6334683895111084,
 'eval_accuracy': 0.9,
 'eval_runtime': 0.5834,
 'eval_samples_per_second': 102.849,
 'eval_steps_per_second': 25.712,
 'epoch': 3.0}

In [ ]:
predictions_output = trainer.predict(tokenized_test)

logits = predictions_output.predictions
true_labels = predictions_output.label_ids

predicted_labels = np.argmax(logits, axis=-1)

In [ ]:
target_names = ["kinase", "GPCR", "ion_channel"]

report = classification_report(
    true_labels,
    predicted_labels,
    target_names=target_names
)

print(report)

              precision    recall  f1-score   support

      kinase       0.90      0.90      0.90        20
        GPCR       0.90      0.95      0.93        20
 ion_channel       0.89      0.85      0.87        20

    accuracy                           0.90        60
   macro avg       0.90      0.90      0.90        60
weighted avg       0.90      0.90      0.90        60

In [ ]:
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
import matplotlib.pyplot as plt

In [ ]:
cm = confusion_matrix(true_labels, predicted_labels)

disp = ConfusionMatrixDisplay(
    confusion_matrix=cm,
    display_labels=target_names
)

disp.plot()
plt.title("Confusion Matrix: Drug Target Class Prediction")
plt.show()

In [ ]:
from sklearn.metrics import precision_recall_fscore_support

precision, recall, f1, support = precision_recall_fscore_support(
    true_labels,
    predicted_labels,
    labels=[0, 1, 2]
)

metrics_df = pd.DataFrame({
    "class": target_names,
    "precision": precision,
    "recall": recall,
    "f1_score": f1,
    "support": support
})

metrics_df

         class  precision  recall  f1_score  support
0       kinase   0.900000    0.90  0.900000       20
1         GPCR   0.904762    0.95  0.926829       20
2  ion_channel   0.894737    0.85  0.871795       20

In [ ]:
plt.figure(figsize=(6,4))
plt.bar(metrics_df["class"], metrics_df["f1_score"])
plt.ylim(0, 1)
plt.ylabel("F1-score")
plt.title("F1-score per Drug Target Class")
plt.show()

In [ ]:
trainer.save_model("./final_drug_target_model")
tokenizer.save_pretrained("./final_drug_target_model")

('./final_drug_target_model/tokenizer_config.json',
 './final_drug_target_model/vocab.txt',
 './final_drug_target_model/added_tokens.json')

In [ ]:
label_map = {
    0: "kinase",
    1: "GPCR",
    2: "ion_channel"
}

def predict_drug_target_class(sequence):
    inputs = tokenizer(
        sequence,
        return_tensors="pt",
        truncation=True,
        padding=True,
        max_length=512
    )

    inputs = {key: value.to(model.device) for key, value in inputs.items()}

    outputs = model(**inputs)

    predicted_label = np.argmax(outputs.logits.detach().cpu().numpy(), axis=-1)[0]

    return label_map[predicted_label]

In [ ]:
test_sequence = "MELRVLLCWASLAAALEETLLNTKLETADLKWVTFPQVDGQWEELSGLDEEQHSVRTYEVCDGPGD"

prediction = predict_drug_target_class(test_sequence)

print("Predicted drug target class:", prediction)

Predicted drug target class: kinase

In [ ]:
trainer.save_model("./final_drug_target_model")
tokenizer.save_pretrained("./final_drug_target_model")

('./final_drug_target_model/tokenizer_config.json',
 './final_drug_target_model/vocab.txt',
 './final_drug_target_model/added_tokens.json')

In [ ]:
!zip -r final_drug_target_model.zip final_drug_target_model

  adding: final_drug_target_model/ (stored 0%)
  adding: final_drug_target_model/model.safetensors (deflated 7%)
  adding: final_drug_target_model/vocab.txt (deflated 6%)
  adding: final_drug_target_model/config.json (deflated 55%)
  adding: final_drug_target_model/training_args.bin (deflated 53%)
  adding: final_drug_target_model/tokenizer_config.json (deflated 76%)

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import nbformat

notebook_path =/content/drive/MyDrive/Colab Notebooks/ESM2_Drug_Target_Class_Prediction.ipynb

nb = nbformat.read(notebook_path, as_version=4)

if "widgets" in nb.metadata:
    del nb.metadata["widgets"]

nbformat.write(nb, notebook_path)

print("Notebook cleaned successfully!")

SyntaxError: invalid syntax (2961150431.py, line 3)